global:
  device: 0
  mode: train  # ['train', 'eval']
  formulation: p(y|y_sparse_cn)

model:
  name: ours
  pretrained: True
  weights:
  config:

surrogate:
  name: older_surrogate_mh
  weights:

training:
  batch_size: 1
  steps_per_epoch: 1024
  epochs: 50
  loss: L1
  lr: 1e-4
  optimizer: Adam

validation:
  batch_size: 1
  steps_per_epoch: 256
  loss: L1

dataset:
  name: MOS2SEFDataset
  image_size: 512
  crop_size: 128
  num_workers: 0
  masking_ratio: 16

logging:
  root: "/playpen/mufan/levi/tianlong-chen-lab/material-super-resolution/__exps__/__controlnet_runs__"
  exp_name: controlnet-unconditional
  result_columns: []
  save_weights: true
  save_only_best_weights: true
  enable_tensorboard: false
  log_figures: false
  log_interval: 100