weights_fp: "/playpen/mufan/levi/tianlong-chen-lab/material-super-resolution/_SwinIR/__weights__/005_colorDN_DFWB_s128w8_SwinIR-M_noise25.pth"
hyperparams:
  upscale: 8
  img_size: [128, 128]
  window_size: 8
  img_range: 1.0
  depths: [6, 6, 6, 6, 6, 6] # DEFAULT: [8, 8, 8, 8, 8, 8]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  drop_path_rate: 0.1
  norm_layer: torch.nn.LayerNorm
  upsampler: "no_upscale"
  resi_connection: "1conv"