global:
  device: 0
  mode: train  # ['train', 'eval']
  formulation: 2x-sr

model:
  # pretrained: True
  name: ours
  weights:
  config: model-configs/001_classic_img_sr-2x-sr64.yaml
  # config: model-configs/001_classic_img_sr-8x-s48.yaml
  # config: model-configs/001_classic_img_sr-4x-s64.yaml

training:
  batch_size: 1
  steps_per_epoch: 1024
  epochs: 2000
  loss: L1
  lr: 1e-5
  optimizer: Adam

validation:
  batch_size: 1
  steps_per_epoch: 256
  loss: L1

dataset:
  name: MOS2SRDataset
  image_size: 512
  crop_size: 128
  num_workers: 0
  masking_ratio: 1

logging:
  root: "__exps__/y-task-formulations/2x-sr"
  exp_name: swinir-2x-sr
  result_columns: []
  save_weights: true
  save_only_best_weights: true
  enable_tensorboard: false
  log_figures: false
  log_interval: 1